# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: v1
kind: Service
metadata:
  name: backend-internal
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - 
    name: http
    port: 8080
    targetPort: 8080